import type { Dialect } from "../dialects/dialect";
import type { ForeignKey, Index, Schema, Table } from "../ir/types";

export interface EmitOptions {
  ifNotExists?: boolean;
}

/**
 * Emit DDL for a schema in the given dialect. Postgres/MySQL emit foreign keys
 * as ALTER statements (ordering-safe); SQLite emits them inline in CREATE TABLE.
 * Feature-gap warnings are prepended as `-- ⚠` comments.
 */
export function emitDdl(schema: Schema, dialect: Dialect, options: EmitOptions = {}): string {
  const header = [
    `-- generated by SchemaGuard · target: ${dialect.label}`,
    ...dialect.warnings(schema).map((w) => `-- ⚠ ${w}`),
  ].join("\n");

  const blocks: string[] = [header];

  for (const table of schema.tables) {
    blocks.push(emitCreateTable(table, dialect, options));
  }
  if (!dialect.foreignKeysInline) {
    for (const table of schema.tables) {
      for (const fk of table.foreignKeys) {
        blocks.push(emitAlterFk(table, fk, dialect));
      }
    }
  }
  for (const table of schema.tables) {
    for (const index of table.indexes) {
      blocks.push(emitIndex(table, index, dialect));
    }
  }

  return blocks.join("\n\n") + "\n";
}

function fkClause(fk: ForeignKey, dialect: Dialect): string {
  const q = (n: string): string => dialect.quoteIdent(n);
  let s =
    `FOREIGN KEY (${fk.columns.map(q).join(", ")}) ` +
    `REFERENCES ${q(fk.refTable)} (${fk.refColumns.map(q).join(", ")})`;
  if (fk.onDelete) s += ` ON DELETE ${fk.onDelete.toUpperCase()}`;
  if (fk.onUpdate) s += ` ON UPDATE ${fk.onUpdate.toUpperCase()}`;
  return s;
}

function emitCreateTable(table: Table, dialect: Dialect, options: EmitOptions): string {
  const q = (n: string): string => dialect.quoteIdent(n);
  const singlePk =
    table.primaryKey && table.primaryKey.length === 1 ? table.primaryKey[0] : undefined;

  let pkInlineHandled = false;
  const lines = table.columns.map((column) => {
    const r = dialect.columnSql(column, column.name === singlePk);
    if (r.pkInline) pkInlineHandled = true;
    return `  ${r.sql}`;
  });

  if (table.primaryKey && table.primaryKey.length > 0 && !pkInlineHandled) {
    lines.push(`  PRIMARY KEY (${table.primaryKey.map(q).join(", ")})`);
  }
  if (dialect.foreignKeysInline) {
    for (const fk of table.foreignKeys) {
      lines.push(`  ${fkClause(fk, dialect)}`);
    }
  }

  const ine = options.ifNotExists && dialect.ifNotExists ? "IF NOT EXISTS " : "";
  return `CREATE TABLE ${ine}${q(table.name)} (\n${lines.join(",\n")}\n);`;
}

function emitAlterFk(table: Table, fk: ForeignKey, dialect: Dialect): string {
  const q = (n: string): string => dialect.quoteIdent(n);
  const name = fk.name ?? `${table.name}_${fk.columns.join("_")}_fk`;
  return `ALTER TABLE ${q(table.name)} ADD CONSTRAINT ${q(name)}\n  ${fkClause(fk, dialect)};`;
}

function emitIndex(table: Table, index: Index, dialect: Dialect): string {
  const q = (n: string): string => dialect.quoteIdent(n);
  const name = index.name ?? `${table.name}_${index.columns.join("_")}_idx`;
  const unique = index.unique ? "UNIQUE " : "";
  return `CREATE ${unique}INDEX ${q(name)} ON ${q(table.name)} (${index.columns.map(q).join(", ")});`;
}
